mysql:
 host: "localhost"
 port: 3306
 database: "minecraft"
 username: "user"
 password: "password"
 prefix: "sv_"

protected-blocks:
 - CHEST
 - TRAPPED_CHEST
 - FURNACE
 - BURNING_FURNACE
 - BREWING_STAND
 - HOPPER
 - DISPENCER
 - DROPPER
 - WHITE_SHULKER_BOX
 - ORANGE_SHULKER_BOX
 - MAGENTA_SHULKER_BOX
 - LIGHT_BLUE_SHULKER_BOX
 - YELLOW_SHULKER_BOX
 - PINK_SHULKER_BOX
 - GRAY_SHULKER_BOX
 - SILVER_SHULKER_BOX
 - CYAN_SHULKER_BOX
 - PURPLE_SHULKER_BOX
 - BLUE_SHULKER_BOX
 - BROWN_SHULKER_BOX
 - GREEN_SHULKER_BOX
 - RED_SHULKER_BOX
 - BLACK_SHULKER_BOX
 - STORAGE_MINECART
 - POWERED_MINECART
 - HOPPER_MINECART
 - ITEM_FRAME

auto-protected-blocks:
 - CHEST
 - TRAPPED_CHEST

message:
  incorrect-param: "&cParametro non corretto"
  incorrect-usage: "&cUso scorretto! Usa così il comando: &e{command}"
  insufficient-perm: "&cNon hai il permesso di eseguire questo comando!"
  not-player: "&cDevi essere un player per eseguire questo comando!"
  player-not-found: "&cQuesto player non esiste!"
  protect-added: "&9Il blocco, &f{block}&9, ora è protetto!"
  protect-allowed-added: "&9Questo player ora ha accesso alle tue protezioni!"
  protect-allowed-already: "&cQuesto player ha già accesso alle tue protezioni!"
  protect-allowed-none: "&cQuesto player non ha accesso alle tue protezioni!"
  protect-allowed-override: "&9Ora il player {player} non ha più accesso alle tue protezioni."
  protect-allowed-removed: "&9Questo player non ha più accesso alle tue protezioni!"
  protect-already: "&cQuesto blocco è già protetto!"
  protect-incompatible: "&cNon puoi proteggere questo tipo di blocchi!"
  protect-inexistent: "&cQuesto blocco non è protetto!"
  protect-perm-denied: "&cNon hai il permesso di eseguire questa operazione!"
  protect-pointer: "&cDevi usare questo comando puntando un blocco!"
  protect-private: "&9Il blocco, &f{block}&9, può ora può essere aperto solo da te!"
  protect-private-warn: "&cQuesto blocco è privato!"
  protect-public: "&9Il blocco, &f{block}&9, può ora può essere aperto secondo le tue impostazioni!"
  protect-removed: "&9Il blocco, &f{block}&9, non è più protetto"
  protect-team-allowed: "&9Ora il tuo team può accedere alle tue protezioni secondo le tue impostazioni!"
  protect-team-denied: "&9Il tuo team non può più accedere alle tue protezioni!"
  pvp-actived: "&6&lPvP &2attivato"
  pvp-deactived: "&6&lPvP &4disattivato"
  team-already: "&cIl player è già in un team!"
  team-created: "&9Hai creato il team &f&l{name}&9!"
  team-denied-perm: "&cDevi essere il leader del team per eseguire questo comando!"
  team-disbanded: "&9Team cancellato"
  team-exists: "&cEsiste già un team con questo nome!"
  team-inexistent: "&cTeam inesistente!"
  team-invite: "&9Hai ricevuto un invito ad entrare nel team &f&l{name}&9. Usa il comando &f/team accept &9per accettare la richiesta!"
  team-invite-sent: "&9Hai inviato la richiesta a &f{player}&9!"
  team-join: "&9Sei entrato nel team &f&l{name}&9!"
  team-joined: "&f{player} &9 è entrato nel team!"
  team-nothing: "&cNon sei in nessun team!"
  team-not-your: "&cQuesto player non è nel tuo team!"
  team-pending-none: "&cNon hai nessuna richiesta d team!"
  team-remove: "&9Hai rimosso &f{player} &9dal tuo team!"
  team-removed: "&cSei stato rimosso dal team &f&l{name}&c!"
  ticket-list: "&f[&9{code}&f] &9&l{player} &f[&9x&f:&b{x}&f, &9y&f:&b{y}&f, &9z&f:&b{z}&f] &9: &f{message}"
  ticket-nothing: "&cNon hai selezionato nessun ticket!"
  ticket-notify: "&f[&9{code}&f] &9&l{player} &bha aperto un ticket con messaggio: &f{message}"
  ticket-open: "&2Hai inviato il ticket, il codice di riferimento è &e{code} &2conservalo per facilitare le operazioni di assistenza"
  ticket-solve: "&f[&9{code}&f] &9&l{player} &f: {message}"
  ticket-solved: "&9Ticket &f{code} &9risolto"
  ticket-solving: "&cPuoi risolvere un solo ticket alla volta!"
  ticket-solving-notify: "&9{player} &fsta risolvendo il ticket numero &9{code}&f!"
  ticket-unsolve: "&cPuoi usare questo comando solo se stai risolvendo un ticket. L'id che inserisci deve essere uguale a quello del ticket che stai risolvendo"
  ticket-unsolved: "&9Ticket &f{code} &9non risolto"

welcome-message: "&2Ciao, benvenuto in &aDeliriumCraft&2! Ricordati che puoi usare il comando &e/ticket &2 per aprire una segnalazione &7(Ogni abuso verrà punito)&2. Quando posizioni una cassa, essa verrà protetta in automatico, usa il comando &e/protect help &2per maggiori informazioni oppure contatta lo staff."